// app/lib/demo.ts
import type { TorAnalysisResult } from './types'

export const DEMO_TOR_TEXT = `Terms of Reference (TOR) - ระบบบริการดิจิทัลสำหรับประชาชน

1. ภาพรวมโครงการ
โครงการพัฒนาระบบบริการดิจิทัลแบบครบวงจรผ่าน LINE LIFF และเว็บไซต์
ระยะเวลา 9 เดือน เริ่ม 1 มิ.ย. 2569 สิ้นสุด 28 ก.พ. 2570 จำนวน 4 งวดงาน

2. ข้อกำหนดระบบ
2.1 รองรับผู้ใช้พร้อมกัน LIFF >= 10,000 / Admin >= 500
2.2 ตรวจสอบความปลอดภัยด้วย Fortify, Black Duck, WebInspect

3. ระบบที่ต้องพัฒนา
3.1 Frontend LINE LIFF (Nuxt 3 + Vue 3)
3.2 Core API Backend (NestJS + PostgreSQL)
3.3 Admin Backoffice Dashboard (Next.js + Tailwind)

4. External Integrations
4.1 LINE Messaging API, 4.2 Thai Gov Open Data, 4.3 Omise Payment, 4.4 SMS OTP Gateway`

export const DEMO_RESULT: TorAnalysisResult = {
  project_overview: {
    project_name: 'ระบบบริการดิจิทัลสำหรับประชาชนแบบครบวงจร',
    description: 'พัฒนาแพลตฟอร์มบริการดิจิทัลสำหรับประชาชนผ่าน LINE LIFF, Web Application และ Admin Backoffice ครอบคลุมการนัดหมายออนไลน์ การแจ้งเตือน และการชำระเงิน โดยเชื่อมต่อกับระบบภายนอกอย่างครบถ้วนและมีมาตรฐานความปลอดภัยระดับองค์กร',
    objective: 'ยกระดับคุณภาพการให้บริการภาครัฐด้วยระบบดิจิทัลที่ประชาชนสามารถเข้าถึงได้ผ่าน LINE LIFF และ Web Browser โดยไม่ต้องเดินทางมาที่สำนักงาน',
    scope: 'พัฒนาระบบ 3 ส่วนหลัก ได้แก่ Frontend LIFF App, Core API Backend และ Admin Dashboard พร้อมเชื่อมต่อ External API จำนวน 4 ระบบ',
    stakeholders: ['กรมพัฒนาดิจิทัลเพื่อเศรษฐกิจและสังคม', 'ประชาชนผู้ใช้บริการ', 'เจ้าหน้าที่รัฐ', 'ผู้บริหารโครงการ'],
    budget_thb: '12,500,000 บาท',
    timeline: {
      kickoff_date: '1 มิ.ย. 2569',
      duration_months: 9,
      total_installments: 4,
      go_live_target: 'ภายใน 28 ก.พ. 2570',
    },
    compliance_and_targets: {
      security_requirements: ['Fortify', 'Black Duck', 'WebInspect'],
      concurrent_users_target: 'LIFF ≥ 10,000 | Admin ≥ 500 concurrent',
    },
  },
  metrics: {
    total_systems: 3,
    total_modules: 12,
    total_external_apis: 4,
    total_phases: 4,
    total_sprints: 10,
    total_tasks: 48,
    total_mandays: 240,
    estimated_budget_thb: '12,500,000 บาท',
  },
  systems: [
    {
      system_id: 'S1',
      system_name: 'Frontend LINE LIFF Application',
      system_type: 'Frontend',
      suggested_tech_stack: 'Nuxt 3 + Vue 3 + Pinia + PrimeVue',
      architecture_pattern: 'Component-Based + Composable Pattern',
      deployment_target: 'Vercel / Firebase Hosting',
      modules: [
        {
          module_code: 'M1.1',
          module_name: 'LINE Login & LIFF Initialization',
          tor_reference: 'ข้อ 3.1.1',
          priority: 'Critical',
          estimated_days: 5,
          implementation_details: [
            'เรียก liff.init() ด้วย LIFF ID ที่ลงทะเบียนบน LINE Developers Console',
            'ตรวจสอบ liff.isLoggedIn() และ Redirect ไป LINE Login หากยังไม่ได้ล็อกอิน',
            'ดึง Profile และ Access Token เพื่อส่ง verify ที่ Backend',
            'จัดการ liff.closeWindow() สำหรับ Native Mode',
            'รองรับ liff.scanCodeV2() สำหรับสแกน QR Code',
          ],
          acceptance_criteria: [
            'ผู้ใช้สามารถ Login ผ่าน LINE ได้ภายใน 3 วินาที',
            'Token refresh อัตโนมัติก่อนหมดอายุ',
            'ทดสอบบน iOS และ Android ผ่าน 100%',
          ],
          risks: ['LINE SDK version update อาจทำให้ API เปลี่ยน'],
          dependencies: [],
        },
        {
          module_code: 'M1.2',
          module_name: 'หน้าแสดงรายการบริการประชาชน',
          tor_reference: 'ข้อ 3.1.2',
          priority: 'High',
          estimated_days: 8,
          implementation_details: [
            'แสดงรายการบริการแบบ Card Grid พร้อมฟิลเตอร์และค้นหา',
            'ดึงข้อมูลบริการผ่าน REST API พร้อม Infinite Scroll',
            'รองรับ Skeleton Loading และ Error Boundary',
            'Cache ข้อมูลด้วย TanStack Query / Pinia persist',
            'รองรับหลายภาษา (ไทย / English)',
          ],
          acceptance_criteria: [
            'โหลดหน้าแรกไม่เกิน 2 วินาที',
            'รองรับ offline mode แสดงข้อมูล cache',
            'Accessibility ผ่าน WCAG 2.1 AA',
          ],
          risks: ['ข้อมูลบริการเปลี่ยนบ่อย ต้องมี cache invalidation'],
          dependencies: ['M2.2'],
        },
        {
          module_code: 'M1.3',
          module_name: 'ระบบนัดหมายออนไลน์',
          tor_reference: 'ข้อ 3.1.3',
          priority: 'Critical',
          estimated_days: 12,
          implementation_details: [
            'ปฏิทินเลือกวัน/เวลานัดหมายแบบ Real-time Availability',
            'กรอกแบบฟอร์มข้อมูลผู้ใช้พร้อม Validation ด้วย Zod',
            'ยืนยันการนัดหมายและส่ง Confirmation ผ่าน LINE Notification',
            'แสดงขั้นตอนแบบ Stepper UI (เลือกวัน → กรอกข้อมูล → ยืนยัน)',
            'รองรับการยกเลิกและเลื่อนนัดหมาย',
          ],
          acceptance_criteria: [
            'Booking สำเร็จภายใน 30 วินาที',
            'ระบบ prevent double booking 100%',
            'ส่ง LINE Notification ภายใน 5 วินาทีหลัง confirm',
          ],
          risks: ['Race condition ในการจอง slot เดียวกัน'],
          dependencies: ['M1.1', 'M2.2'],
        },
        {
          module_code: 'M1.4',
          module_name: 'ระบบชำระเงินและแจ้งเตือน',
          tor_reference: 'ข้อ 3.1.4',
          priority: 'High',
          estimated_days: 10,
          implementation_details: [
            'เชื่อมต่อ Omise Payment Gateway สำหรับชำระค่าบริการ',
            'แสดงประวัติการนัดหมายและสถานะการชำระเงิน',
            'แสดง Receipt และ QR Code หลังชำระ',
            'รองรับ PromptPay QR และบัตรเครดิต',
            'ส่ง Push Notification แจ้งเตือนผ่าน LINE',
          ],
          acceptance_criteria: [
            'Payment success rate ≥ 99.5%',
            'Receipt ออกภายใน 3 วินาทีหลังชำระ',
            'PCI DSS compliant',
          ],
          risks: ['Omise downtime กระทบ payment flow'],
          dependencies: ['M1.3', 'M2.3'],
        },
      ],
    },
    {
      system_id: 'S2',
      system_name: 'Core API Backend',
      system_type: 'Backend',
      suggested_tech_stack: 'NestJS + TypeORM + PostgreSQL + Redis',
      architecture_pattern: 'Layered Architecture + Repository Pattern',
      deployment_target: 'AWS ECS / GCP Cloud Run',
      modules: [
        {
          module_code: 'M2.1',
          module_name: 'Authentication & Authorization',
          tor_reference: 'ข้อ 3.2.1',
          priority: 'Critical',
          estimated_days: 10,
          implementation_details: [
            'ตรวจสอบ LINE Access Token ผ่าน LINE Verify API',
            'ออก JWT (Access + Refresh Token) และจัดการ Session ผ่าน Redis',
            'กำหนด Role-Based Access Control: CITIZEN, OFFICER, ADMIN',
            'Rate limiting ป้องกัน Brute Force ด้วย Redis',
            'Audit Log บันทึกทุก authentication event',
          ],
          acceptance_criteria: [
            'JWT expire อัตโนมัติใน 1 ชั่วโมง',
            'Refresh Token rotate ทุกครั้งที่ใช้',
            'ผ่าน Penetration Test จาก Fortify',
          ],
          risks: ['LINE Token format อาจเปลี่ยนใน API version ใหม่'],
          dependencies: [],
        },
        {
          module_code: 'M2.2',
          module_name: 'Appointment Management API',
          tor_reference: 'ข้อ 3.2.2',
          priority: 'Critical',
          estimated_days: 15,
          implementation_details: [
            'CRUD Endpoints สำหรับการจัดการนัดหมาย',
            'ระบบ Slot Availability และ Conflict Detection แบบ Real-time',
            'Optimistic Locking ป้องกัน Race Condition',
            'Webhook สำหรับแจ้ง downstream systems',
            'Pagination, Filtering และ Sorting ทุก endpoint',
          ],
          acceptance_criteria: [
            'API response time ≤ 200ms (p95)',
            'รองรับ 500 concurrent booking requests',
            'Zero double booking ในทุก scenario',
          ],
          risks: ['Database deadlock หาก transaction ไม่ถูก design ดี'],
          dependencies: ['M2.1'],
        },
        {
          module_code: 'M2.3',
          module_name: 'Notification & Messaging Service',
          tor_reference: 'ข้อ 3.2.3',
          priority: 'High',
          estimated_days: 8,
          implementation_details: [
            'เชื่อมต่อ LINE Messaging API ส่ง Push/Reply Message',
            'Queue-based Notification ผ่าน Bull + Redis',
            'Template Engine สำหรับ Flex Message',
            'Retry mechanism สำหรับ failed notifications',
            'Dashboard แสดง delivery status',
          ],
          acceptance_criteria: [
            'Notification delivery rate ≥ 99%',
            'ส่งสำเร็จภายใน 5 วินาที',
            'Failed messages retry อัตโนมัติ 3 ครั้ง',
          ],
          risks: ['LINE API rate limit 1000 messages/min'],
          dependencies: ['M2.1'],
        },
        {
          module_code: 'M2.4',
          module_name: 'Report & Analytics API',
          tor_reference: 'ข้อ 3.2.4',
          priority: 'Medium',
          estimated_days: 8,
          implementation_details: [
            'Aggregation Query สำหรับ Dashboard Metrics',
            'Export ข้อมูลเป็น CSV/Excel ด้วย ExcelJS',
            'Scheduled Report ส่งอีเมลรายวัน/สัปดาห์',
            'Cache query results ด้วย Redis TTL 5 นาที',
            'Custom date range filtering',
          ],
          acceptance_criteria: [
            'Report generate ไม่เกิน 10 วินาที สำหรับข้อมูล 1 ปี',
            'Export Excel ไม่เกิน 50,000 rows',
            'ข้อมูล real-time lag ≤ 1 นาที',
          ],
          risks: ['Large dataset query อาจ timeout'],
          dependencies: ['M2.1', 'M2.2'],
        },
      ],
    },
    {
      system_id: 'S3',
      system_name: 'Admin Backoffice Dashboard',
      system_type: 'Frontend',
      suggested_tech_stack: 'Next.js 14 + TypeScript + Tailwind CSS + shadcn/ui',
      architecture_pattern: 'App Router + Server Components',
      deployment_target: 'Vercel / AWS Amplify',
      modules: [
        {
          module_code: 'M3.1',
          module_name: 'User & Role Management',
          tor_reference: 'ข้อ 3.3.1',
          priority: 'High',
          estimated_days: 8,
          implementation_details: [
            'ตารางแสดงรายชื่อผู้ใช้พร้อม Filter, Search และ Pagination',
            'จัดการสิทธิ์ผู้ใช้แบบ RBAC ผ่าน Role Assignment',
            'Import ผู้ใช้จาก Excel/CSV',
            'Activity Log แสดงประวัติการเข้าใช้งาน',
            'Two-Factor Authentication สำหรับ Admin',
          ],
          acceptance_criteria: [
            'โหลดตาราง 10,000 records ไม่เกิน 3 วินาที',
            'Role change มีผลทันทีโดยไม่ต้อง logout',
            'ผ่าน Black Duck security scan',
          ],
          risks: ['Permission conflict หากมีหลาย role ต่อ user'],
          dependencies: ['M2.1'],
        },
        {
          module_code: 'M3.2',
          module_name: 'Appointment Calendar Management',
          tor_reference: 'ข้อ 3.3.2',
          priority: 'High',
          estimated_days: 10,
          implementation_details: [
            'ปฏิทินแบบ Month/Week/Day View ด้วย FullCalendar',
            'Drag-and-drop รีเซตนัดหมาย พร้อม Conflict Alert',
            'Bulk action: ยืนยัน/ยกเลิกนัดหมายพร้อมกัน',
            'Print/Export ตาราง appointment รายวัน',
            'Real-time update ผ่าน WebSocket',
          ],
          acceptance_criteria: [
            'Calendar โหลดข้อมูล 1 เดือนไม่เกิน 2 วินาที',
            'Drag-and-drop สำเร็จ 100% โดยไม่เกิด double booking',
          ],
          risks: ['FullCalendar license cost สำหรับ Premium features'],
          dependencies: ['M2.2'],
        },
        {
          module_code: 'M3.3',
          module_name: 'Analytics Dashboard',
          tor_reference: 'ข้อ 3.3.3',
          priority: 'Medium',
          estimated_days: 8,
          implementation_details: [
            'KPI Cards แสดง Real-time Metrics',
            'Chart แสดงแนวโน้มด้วย Recharts',
            'Heatmap แสดง peak hours',
            'Funnel chart แสดง conversion rate',
            'Drill-down จาก summary ถึง transaction level',
          ],
          acceptance_criteria: [
            'Dashboard refresh อัตโนมัติทุก 30 วินาที',
            'Chart render ไม่เกิน 1 วินาที',
          ],
          risks: ['ข้อมูล realtime อาจ lag ในช่วง peak'],
          dependencies: ['M2.4'],
        },
        {
          module_code: 'M3.4',
          module_name: 'Content Management System',
          tor_reference: 'ข้อ 3.3.4',
          priority: 'Medium',
          estimated_days: 7,
          implementation_details: [
            'Rich Text Editor สำหรับจัดการเนื้อหาบริการ',
            'อัปโหลดและจัดการไฟล์ผ่าน S3-compatible Storage',
            'Version control เนื้อหา ย้อนกลับได้',
            'Preview ก่อน publish',
            'Schedule publish สำหรับเนื้อหาล่วงหน้า',
          ],
          acceptance_criteria: [
            'Upload ไฟล์ได้ไม่เกิน 50MB',
            'Image auto-optimize ลดขนาดก่อน save',
          ],
          risks: ['Storage cost เพิ่มตามจำนวนไฟล์'],
          dependencies: ['M2.1'],
        },
      ],
    },
  ],
  external_apis: [
    {
      api_name: 'LINE Messaging API & LIFF SDK',
      purpose: 'รับ-ส่งข้อความ Push/Reply และเปิด LIFF Application ในแอป LINE',
      associated_module_code: 'M1.1, M2.3',
      security_protocol: 'HMAC-SHA256 Webhook + Bearer Token',
      integration_type: 'REST',
      data_flow: 'ส่ง Push Message → LINE Platform → ผู้ใช้',
      sla_requirement: 'Delivery ≥ 99% ใน 5 วินาที',
    },
    {
      api_name: 'Thai Government Open Data API',
      purpose: 'ดึงข้อมูลทะเบียนราษฎร์เพื่อยืนยันตัวตนผู้ใช้งาน',
      associated_module_code: 'M2.1',
      security_protocol: 'OAuth 2.0 + TLS 1.3',
      integration_type: 'REST',
      data_flow: 'ส่ง ID Card → รับ ชื่อ/นามสกุล/ที่อยู่',
      sla_requirement: 'Response ≤ 3 วินาที',
    },
    {
      api_name: 'Omise Payment Gateway',
      purpose: 'ประมวลผลการชำระเงิน รองรับบัตรเครดิต, QR Code, PromptPay',
      associated_module_code: 'M1.4',
      security_protocol: 'HTTPS + PCI DSS + Webhook HMAC',
      integration_type: 'REST',
      data_flow: 'ส่ง charge request → รับ payment status + receipt',
      sla_requirement: 'Success rate ≥ 99.5%',
    },
    {
      api_name: 'SMS OTP Gateway',
      purpose: 'ส่ง OTP สำหรับยืนยันเบอร์โทรศัพท์ในขั้นตอนลงทะเบียน',
      associated_module_code: 'M2.1',
      security_protocol: 'HTTPS REST + API Key Rotation',
      integration_type: 'REST',
      data_flow: 'ส่ง phone number → SMS OTP → รับ verify code',
      sla_requirement: 'Delivery ≤ 30 วินาที',
    },
  ],
  sprint_backlog: [
    {
      sprint_number: 1, duration_weeks: 2, start_week: 1, end_week: 2,
      focus: 'Project Setup, CI/CD Pipeline, Infrastructure, DB Schema',
      goals: ['Setup Git repository และ branching strategy', 'Configure CI/CD ด้วย GitHub Actions', 'สร้าง DB Schema ทั้งหมด', 'Deploy environment: Dev, Staging, Prod'],
      associated_module_codes: ['M2.1'],
      daily_schedule: [
        { day: 1, date_offset: 'วันที่ 1 (จ. สัปดาห์ที่ 1)', tasks: ['Kickoff meeting ทีม', 'ตั้งค่า Git repo และ branching'], deliverables: ['Git repository พร้อม branch strategy'], assignee_role: 'Tech Lead' },
        { day: 2, date_offset: 'วันที่ 2 (อ. สัปดาห์ที่ 1)', tasks: ['Setup Docker compose local', 'Configure ESLint, Prettier, Husky'], deliverables: ['Local dev environment'], assignee_role: 'DevOps + Dev' },
        { day: 3, date_offset: 'วันที่ 3 (พ. สัปดาห์ที่ 1)', tasks: ['Setup CI/CD GitHub Actions', 'Configure staging server'], deliverables: ['Auto deploy pipeline'], assignee_role: 'DevOps' },
        { day: 4, date_offset: 'วันที่ 4 (พฤ. สัปดาห์ที่ 1)', tasks: ['ออกแบบ DB Schema', 'เขียน migration scripts'], deliverables: ['DB Schema document'], assignee_role: 'Backend Dev' },
        { day: 5, date_offset: 'วันที่ 5 (ศ. สัปดาห์ที่ 1)', tasks: ['Setup NestJS project structure', 'Configure TypeORM + PostgreSQL'], deliverables: ['NestJS boilerplate ready'], assignee_role: 'Backend Dev' },
        { day: 6, date_offset: 'วันที่ 6 (จ. สัปดาห์ที่ 2)', tasks: ['Setup Nuxt 3 project', 'Configure Pinia + PrimeVue'], deliverables: ['Frontend boilerplate'], assignee_role: 'Frontend Dev' },
        { day: 7, date_offset: 'วันที่ 7 (อ. สัปดาห์ที่ 2)', tasks: ['Setup Next.js Admin project', 'Configure Tailwind + shadcn/ui'], deliverables: ['Admin boilerplate'], assignee_role: 'Frontend Dev' },
        { day: 8, date_offset: 'วันที่ 8 (พ. สัปดาห์ที่ 2)', tasks: ['Setup Redis + Bull Queue', 'Configure Monitoring (Datadog/Grafana)'], deliverables: ['Infrastructure ready'], assignee_role: 'DevOps' },
        { day: 9, date_offset: 'วันที่ 9 (พฤ. สัปดาห์ที่ 2)', tasks: ['Run migration, seed demo data', 'Test CI/CD pipeline end-to-end'], deliverables: ['DB populated with seed data'], assignee_role: 'Full Team' },
        { day: 10, date_offset: 'วันที่ 10 (ศ. สัปดาห์ที่ 2)', tasks: ['Sprint review', 'Demo environment ให้ผู้บริหาร'], deliverables: ['Sprint 1 report'], assignee_role: 'Tech Lead' },
      ],
      definition_of_done: ['CI/CD deploy อัตโนมัติเมื่อ merge to main', 'DB schema ผ่าน review จาก DBA', 'ทุก environment ทำงานได้'],
      risks: ['Server provisioning อาจล่าช้าจาก procurement'],
    },
    {
      sprint_number: 2, duration_weeks: 2, start_week: 3, end_week: 4,
      focus: 'Authentication, LINE Login, JWT + RBAC',
      goals: ['LINE OAuth integration สมบูรณ์', 'JWT issue/verify flow', 'RBAC 3 roles: CITIZEN, OFFICER, ADMIN'],
      associated_module_codes: ['M1.1', 'M2.1'],
      daily_schedule: [
        { day: 1, date_offset: 'วันที่ 1 (จ. สัปดาห์ที่ 3)', tasks: ['สร้าง LINE Login endpoint', 'Integrate LINE Verify API'], deliverables: ['LINE verify endpoint'], assignee_role: 'Backend Dev' },
        { day: 2, date_offset: 'วันที่ 2 (อ. สัปดาห์ที่ 3)', tasks: ['พัฒนา JWT issue/refresh logic', 'Setup Redis session store'], deliverables: ['JWT auth flow'], assignee_role: 'Backend Dev' },
        { day: 3, date_offset: 'วันที่ 3 (พ. สัปดาห์ที่ 3)', tasks: ['พัฒนา RBAC middleware', 'เขียน Guard สำหรับ NestJS'], deliverables: ['RBAC guards'], assignee_role: 'Backend Dev' },
        { day: 4, date_offset: 'วันที่ 4 (พฤ. สัปดาห์ที่ 3)', tasks: ['พัฒนา LIFF init ใน Nuxt', 'ทำ LINE Login flow บน Frontend'], deliverables: ['LIFF Login UI'], assignee_role: 'Frontend Dev' },
        { day: 5, date_offset: 'วันที่ 5 (ศ. สัปดาห์ที่ 3)', tasks: ['ทดสอบ auth flow บน iOS', 'ทดสอบ auth flow บน Android'], deliverables: ['Cross-platform test pass'], assignee_role: 'QA' },
        { day: 6, date_offset: 'วันที่ 6 (จ. สัปดาห์ที่ 4)', tasks: ['พัฒนา Admin login (email/password)', 'ทำ 2FA สำหรับ ADMIN role'], deliverables: ['Admin auth'], assignee_role: 'Backend + Frontend Dev' },
        { day: 7, date_offset: 'วันที่ 7 (อ. สัปดาห์ที่ 4)', tasks: ['เขียน Unit test auth module', 'เขียน Integration test'], deliverables: ['Test coverage ≥ 80%'], assignee_role: 'Backend Dev' },
        { day: 8, date_offset: 'วันที่ 8 (พ. สัปดาห์ที่ 4)', tasks: ['Setup Rate limiting', 'Configure Audit log'], deliverables: ['Security hardening'], assignee_role: 'Backend Dev' },
        { day: 9, date_offset: 'วันที่ 9 (พฤ. สัปดาห์ที่ 4)', tasks: ['Penetration test เบื้องต้น', 'Fix issues จาก security scan'], deliverables: ['Security report'], assignee_role: 'QA + Dev' },
        { day: 10, date_offset: 'วันที่ 10 (ศ. สัปดาห์ที่ 4)', tasks: ['Sprint review demo', 'Update documentation'], deliverables: ['Auth module complete'], assignee_role: 'Full Team' },
      ],
      definition_of_done: ['LINE Login ทำงานได้บน iOS และ Android', 'JWT expiry และ refresh ทำงานถูกต้อง', 'RBAC ผ่าน test ทุก scenario'],
      risks: ['LINE Developer Console อาจมี LIFF restriction'],
    },
    {
      sprint_number: 3, duration_weeks: 2, start_week: 5, end_week: 6,
      focus: 'LIFF Frontend หลัก, หน้าบริการประชาชน',
      goals: ['หน้าหลัก Service List สมบูรณ์', 'Search & Filter ทำงาน', 'Booking form หน้าแรก'],
      associated_module_codes: ['M1.2', 'M1.3'],
      daily_schedule: [
        { day: 1, date_offset: 'วันที่ 1 (จ. สัปดาห์ที่ 5)', tasks: ['ออกแบบ UI Component library', 'สร้าง Design System'], deliverables: ['Component library'], assignee_role: 'UI/UX + Frontend' },
        { day: 2, date_offset: 'วันที่ 2 (อ. สัปดาห์ที่ 5)', tasks: ['พัฒนา Service List page', 'Integrate API ดึงรายการบริการ'], deliverables: ['Service list working'], assignee_role: 'Frontend Dev' },
        { day: 3, date_offset: 'วันที่ 3 (พ. สัปดาห์ที่ 5)', tasks: ['พัฒนา Search และ Filter', 'Implement Infinite Scroll'], deliverables: ['Search/filter UI'], assignee_role: 'Frontend Dev' },
        { day: 4, date_offset: 'วันที่ 4 (พฤ. สัปดาห์ที่ 5)', tasks: ['Skeleton Loading states', 'Error boundary components'], deliverables: ['Loading/error states'], assignee_role: 'Frontend Dev' },
        { day: 5, date_offset: 'วันที่ 5 (ศ. สัปดาห์ที่ 5)', tasks: ['ทดสอบ performance', 'Optimize bundle size'], deliverables: ['Lighthouse score ≥ 80'], assignee_role: 'Frontend Dev + QA' },
        { day: 6, date_offset: 'วันที่ 6 (จ. สัปดาห์ที่ 6)', tasks: ['พัฒนา Booking Calendar UI', 'Slot availability display'], deliverables: ['Calendar component'], assignee_role: 'Frontend Dev' },
        { day: 7, date_offset: 'วันที่ 7 (อ. สัปดาห์ที่ 6)', tasks: ['พัฒนา Booking form (Stepper)', 'Zod validation schema'], deliverables: ['Booking form'], assignee_role: 'Frontend Dev' },
        { day: 8, date_offset: 'วันที่ 8 (พ. สัปดาห์ที่ 6)', tasks: ['Confirmation screen', 'Success/Error states'], deliverables: ['Booking flow complete'], assignee_role: 'Frontend Dev' },
        { day: 9, date_offset: 'วันที่ 9 (พฤ. สัปดาห์ที่ 6)', tasks: ['E2E test Cypress', 'Mobile responsiveness test'], deliverables: ['E2E test pass'], assignee_role: 'QA' },
        { day: 10, date_offset: 'วันที่ 10 (ศ. สัปดาห์ที่ 6)', tasks: ['Sprint review', 'UAT เบื้องต้นกับผู้ใช้จริง'], deliverables: ['UAT feedback report'], assignee_role: 'PM + QA' },
      ],
      definition_of_done: ['ทุก page โหลด ≤ 2 วินาที', 'รองรับ iOS 15+ และ Android 10+', 'ผ่าน WCAG 2.1 AA'],
      risks: ['UI design revision จาก stakeholder อาจทำให้ล่าช้า'],
    },
  ],
  phases: [
    {
      phase_number: 1, phase_name: 'Infrastructure & Core Auth', duration_weeks: 4, installment_number: 1,
      deliverables: ['ระบบ CI/CD พร้อมใช้งาน', 'Authentication module ครบถ้วน', 'DB Schema สมบูรณ์'],
      payment_percentage: 25,
      key_milestones: ['Deploy to Staging สำเร็จ', 'LINE Login ทำงานได้'],
    },
    {
      phase_number: 2, phase_name: 'Core Features Development', duration_weeks: 10, installment_number: 2,
      deliverables: ['LIFF Application หน้าหลักครบ', 'Booking System สมบูรณ์', 'Admin Dashboard พื้นฐาน'],
      payment_percentage: 35,
      key_milestones: ['Booking flow ครบทุก step', 'Payment integration สำเร็จ'],
    },
    {
      phase_number: 3, phase_name: 'Integration & Advanced Features', duration_weeks: 8, installment_number: 3,
      deliverables: ['External API integrations ครบ', 'Analytics Dashboard', 'Notification system'],
      payment_percentage: 25,
      key_milestones: ['LINE Notification ทำงาน', 'Payment success rate ≥ 99%'],
    },
    {
      phase_number: 4, phase_name: 'UAT & Security & Go-live', duration_weeks: 6, installment_number: 4,
      deliverables: ['ผ่าน Security Audit (Fortify, WebInspect)', 'Load Test 10,000 concurrent users', 'Go-live'],
      payment_percentage: 15,
      key_milestones: ['UAT sign-off จากผู้ว่าจ้าง', 'Go-live สำเร็จ'],
    },
  ],
  risks: [
    { risk_id: 'R1', description: 'LINE SDK version update ทำให้ LIFF API เปลี่ยน', probability: 'Medium', impact: 'High', mitigation: 'Lock SDK version, ติดตาม LINE changelog ทุกสัปดาห์' },
    { risk_id: 'R2', description: 'ระบบ Gov Open Data API ไม่เสถียร', probability: 'High', impact: 'Medium', mitigation: 'Mock API สำหรับ fallback, cache ผลลัพธ์ 24 ชั่วโมง' },
    { risk_id: 'R3', description: 'Load test ไม่ผ่าน 10,000 concurrent users', probability: 'Medium', impact: 'High', mitigation: 'Performance test ทุก sprint, ใช้ horizontal scaling บน ECS' },
    { risk_id: 'R4', description: 'ข้อกำหนดเปลี่ยนระหว่างพัฒนา (Scope Creep)', probability: 'High', impact: 'Medium', mitigation: 'Change request process ชัดเจน, freeze requirement ก่อน Sprint 5' },
  ],
  quotation: {
    quotation_number: 'QT-2569-001',
    quotation_date: '24 มิถุนายน 2569',
    valid_until: '24 กรกฎาคม 2569',
    company_name: 'บริษัท ดิจิทัล โซลูชั่น จำกัด',
    project_name: 'ระบบบริการดิจิทัลสำหรับประชาชนแบบครบวงจร',
    contact_person: 'นาย สมชาย ดิจิทัล (Project Manager)',
    items: [
      { item_code: 'DEV-001', description: 'พัฒนา Frontend LINE LIFF Application (Nuxt 3 + Vue 3)', category: 'Development', quantity: 35, unit: 'MD', unit_price: 3500, total_price: 122500 },
      { item_code: 'DEV-002', description: 'พัฒนา Core API Backend (NestJS + PostgreSQL + Redis)', category: 'Development', quantity: 41, unit: 'MD', unit_price: 4000, total_price: 164000 },
      { item_code: 'DEV-003', description: 'พัฒนา Admin Backoffice Dashboard (Next.js + shadcn/ui)', category: 'Development', quantity: 33, unit: 'MD', unit_price: 3500, total_price: 115500 },
      { item_code: 'DEV-004', description: 'Integration Testing & QA (Manual + Automated)', category: 'Development', quantity: 30, unit: 'MD', unit_price: 2500, total_price: 75000 },
      { item_code: 'DES-001', description: 'UI/UX Design & Prototyping (Figma)', category: 'Design', quantity: 20, unit: 'MD', unit_price: 3000, total_price: 60000 },
      { item_code: 'INF-001', description: 'Cloud Infrastructure Setup (AWS ECS + RDS + ElastiCache)', category: 'Infrastructure', quantity: 3, unit: 'เดือน', unit_price: 45000, total_price: 135000 },
      { item_code: 'INF-002', description: 'CI/CD Pipeline & DevOps Setup', category: 'Infrastructure', quantity: 10, unit: 'MD', unit_price: 4000, total_price: 40000 },
      { item_code: 'LIC-001', description: 'Software Licenses (Monitoring, Testing Tools)', category: 'License', quantity: 1, unit: 'ชุด', unit_price: 80000, total_price: 80000 },
      { item_code: 'TRN-001', description: 'ฝึกอบรมเจ้าหน้าที่ผู้ใช้งานระบบ Admin (2 วัน)', category: 'Training', quantity: 2, unit: 'วัน', unit_price: 25000, total_price: 50000 },
      { item_code: 'SUP-001', description: 'ค่าบำรุงรักษาและสนับสนุนระบบ (หลัง Go-live 3 เดือน)', category: 'Support', quantity: 3, unit: 'เดือน', unit_price: 35000, total_price: 105000 },
    ],
    subtotal: 947000,
    vat_percentage: 7,
    vat_amount: 66290,
    grand_total: 1013290,
    payment_terms: [
      'งวดที่ 1 (25%): ชำระเมื่อลงนามสัญญาและส่งมอบ Infrastructure — 253,322.50 บาท',
      'งวดที่ 2 (35%): ชำระเมื่อส่งมอบ Core Features ผ่านการทดสอบ — 354,651.50 บาท',
      'งวดที่ 3 (25%): ชำระเมื่อ Integration ครบถ้วนและ UAT ผ่าน — 253,322.50 บาท',
      'งวดที่ 4 (15%): ชำระเมื่อ Go-live สำเร็จและส่งมอบเอกสารครบ — 151,993.50 บาท',
    ],
    notes: [
      'ราคานี้ยังไม่รวม Domain, SSL Certificate และค่า External API (LINE, Omise, SMS)',
      'การเปลี่ยนแปลง Scope เกิน 20% จะคิดค่าใช้จ่ายเพิ่มเติมตาม Change Request',
      'รับประกันหลัง Go-live 90 วัน สำหรับ Bug ที่เกิดจากการพัฒนา',
      'ใบเสนอราคามีอายุ 30 วันนับจากวันที่ออก',
    ],
  },
}
